"""initial schema

place if that code is rolled back.

Revision ID: 0001_initial
Revises: 
Create Date: 2026-08-17 18:57:57.516926

EXPAND-ONLY. This migration must be safe to run BEFORE the code that needs it,
and safe to leave in place if that code is rolled back. Additive columns are
nullable or defaulted; drops and tightening belong in a LATER release.
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy
import faue_db.types

revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_memory',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.Text(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('decayed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'tier', 'key', name=op.f('pk_agent_memory')),
    schema='ase'
    )
    op.create_index(op.f('ix_ase_agent_memory_workspace_id'), 'agent_memory', ['workspace_id'], unique=False, schema='ase')
    op.create_table('agent_runs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('trigger', sa.Text(), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('look_id', sa.UUID(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('ran_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs')),
    schema='ase'
    )
    op.create_index(op.f('ix_ase_agent_runs_workspace_id'), 'agent_runs', ['workspace_id'], unique=False, schema='ase')
    op.create_table('aspiration_embeddings',
    sa.Column('pin_id', sa.Text(), nullable=False),
    sa.Column('model_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('board_id', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('pin_id', 'model_id', name=op.f('pk_aspiration_embeddings')),
    schema='ase'
    )
    op.create_index(op.f('ix_ase_aspiration_embeddings_user_id'), 'aspiration_embeddings', ['user_id'], unique=False, schema='ase')
    op.create_index(op.f('ix_ase_aspiration_embeddings_workspace_id'), 'aspiration_embeddings', ['workspace_id'], unique=False, schema='ase')
    op.create_table('budgets',
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('scope_key', sa.Text(), nullable=False),
    sa.Column('period', sa.DateTime(timezone=True), nullable=False),
    sa.Column('spent_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('limit_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.PrimaryKeyConstraint('scope', 'scope_key', 'period', name=op.f('pk_budgets')),
    schema='ase'
    )
    op.create_table('fabric_analyses',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('detected_type', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('user_corrected_type', sa.Text(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suggested_style_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('reasoning_by_style', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fabric_analyses')),
    schema='ase'
    )
    op.create_index(op.f('ix_ase_fabric_analyses_workspace_id'), 'fabric_analyses', ['workspace_id'], unique=False, schema='ase')
    op.create_table('fabric_embeddings',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('asset_id', 'model_id', name=op.f('pk_fabric_embeddings')),
    schema='ase'
    )
    op.create_index(op.f('ix_ase_fabric_embeddings_workspace_id'), 'fabric_embeddings', ['workspace_id'], unique=False, schema='ase')
    op.create_table('look_impressions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('look_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('candidate_set_hash', sa.Text(), nullable=False),
    sa.Column('ranker_version', sa.Text(), nullable=False),
    sa.Column('shown_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_look_impressions')),
    schema='ase'
    )
    op.create_index(op.f('ix_ase_look_impressions_workspace_id'), 'look_impressions', ['workspace_id'], unique=False, schema='ase')
    op.create_table('look_jobs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('request', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('progress', sa.SmallInteger(), nullable=False),
    sa.Column('reason_code', sa.Text(), nullable=True),
    sa.Column('stage_failed', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_look_jobs')),
    schema='ase'
    )
    op.create_index(op.f('ix_ase_look_jobs_status'), 'look_jobs', ['status'], unique=False, schema='ase')
    op.create_index(op.f('ix_ase_look_jobs_user_id'), 'look_jobs', ['user_id'], unique=False, schema='ase')
    op.create_index(op.f('ix_ase_look_jobs_workspace_id'), 'look_jobs', ['workspace_id'], unique=False, schema='ase')
    op.create_table('model_calls',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('tier', sa.Text(), nullable=False),
    sa.Column('model_id', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('fallback_depth', sa.SmallInteger(), nullable=False),
    sa.Column('guardrail_verdict', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_calls')),
    schema='ase'
    )
    op.create_index(op.f('ix_ase_model_calls_created_at'), 'model_calls', ['created_at'], unique=False, schema='ase')
    op.create_index(op.f('ix_ase_model_calls_task'), 'model_calls', ['task'], unique=False, schema='ase')
    op.create_table('outbox',
    sa.Column('event_name', sa.Text(), nullable=False),
    sa.Column('event_version', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('trace_id', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox')),
    schema='ase'
    )
    op.create_index(op.f('ix_ase_outbox_published_at'), 'outbox', ['published_at'], unique=False, schema='ase')
    op.create_table('spree_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('token_spend', sa.Integer(), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spree_sessions')),
    schema='ase'
    )
    op.create_index(op.f('ix_ase_spree_sessions_workspace_id'), 'spree_sessions', ['workspace_id'], unique=False, schema='ase')
    op.create_table('style_embeddings',
    sa.Column('style_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=True),
    sa.PrimaryKeyConstraint('style_id', 'model_id', name=op.f('pk_style_embeddings')),
    schema='ase'
    )
    op.create_table('style_library',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('silhouette', sa.Text(), nullable=False),
    sa.Column('formality', sa.Text(), nullable=False),
    sa.Column('fabric_suitability', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occasion_tags', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('body_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_style_library')),
    schema='ase'
    )
    op.create_table('user_style_context',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dna_vector', pgvector.sqlalchemy.vector.VECTOR(), nullable=True),
    sa.Column('aspiration_vector', pgvector.sqlalchemy.vector.VECTOR(), nullable=True),
    sa.Column('behavior_vector', pgvector.sqlalchemy.vector.VECTOR(), nullable=True),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('wear_count', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stale_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_style_context')),
    schema='ase'
    )
    op.create_index(op.f('ix_ase_user_style_context_workspace_id'), 'user_style_context', ['workspace_id'], unique=False, schema='ase')
    op.create_table('vault_embeddings',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('image_hash', sa.Text(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('item_id', 'model_id', name=op.f('pk_vault_embeddings')),
    schema='ase'
    )
    op.create_index(op.f('ix_ase_vault_embeddings_user_id'), 'vault_embeddings', ['user_id'], unique=False, schema='ase')
    op.create_index(op.f('ix_ase_vault_embeddings_workspace_id'), 'vault_embeddings', ['workspace_id'], unique=False, schema='ase')
    op.create_table('weather_cache',
    sa.Column('geohash5', sa.Text(), nullable=False),
    sa.Column('hour_bucket', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('geohash5', 'hour_bucket', name=op.f('pk_weather_cache')),
    schema='ase'
    )
    op.create_table('admin_users',
    sa.Column('email_enc', faue_db.types.EncryptedStr(), nullable=False),
    sa.Column('email_bidx', faue_db.types.BlindIndex(length=64), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('mfa_enrolled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_users')),
    sa.UniqueConstraint('email_bidx', name=op.f('uq_admin_users_email_bidx')),
    schema='gateway'
    )
    op.create_table('audit_log',
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('actor_role', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('target_type', sa.Text(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log')),
    schema='gateway'
    )
    op.create_index(op.f('ix_gateway_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False, schema='gateway')
    op.create_index(op.f('ix_gateway_audit_log_target_id'), 'audit_log', ['target_id'], unique=False, schema='gateway')
    op.create_table('deletion_ledger',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modules_pending', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('modules_done', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('third_parties_done', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deletion_ledger')),
    schema='gateway'
    )
    op.create_index(op.f('ix_gateway_deletion_ledger_sla_due_at'), 'deletion_ledger', ['sla_due_at'], unique=False, schema='gateway')
    op.create_table('notify_deliveries',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.Text(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notify_deliveries')),
    sa.UniqueConstraint('user_id', 'template_id', 'event_id', name=op.f('uq_notify_deliveries_user_id')),
    schema='gateway'
    )
    op.create_index(op.f('ix_gateway_notify_deliveries_workspace_id'), 'notify_deliveries', ['workspace_id'], unique=False, schema='gateway')
    op.create_table('outbox',
    sa.Column('event_name', sa.Text(), nullable=False),
    sa.Column('event_version', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('trace_id', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox')),
    schema='gateway'
    )
    op.create_index(op.f('ix_gateway_outbox_published_at'), 'outbox', ['published_at'], unique=False, schema='gateway')
    op.create_table('users',
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('age_verified', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    schema='gateway'
    )
    op.create_table('workspaces',
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces')),
    schema='gateway'
    )
    op.create_table('accessory_pairings',
    sa.Column('style_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('occasion', sa.Text(), nullable=True),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['style_id'], ['ase.style_library.id'], name=op.f('fk_accessory_pairings_style_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accessory_pairings')),
    schema='ase'
    )
    op.create_table('looks',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('why_this_works', sa.Text(), nullable=True),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occasion', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('renderer', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('strategy_version', sa.Text(), nullable=False),
    sa.Column('model_id', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['ase.look_jobs.id'], name=op.f('fk_looks_job_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_looks')),
    schema='ase'
    )
    op.create_index(op.f('ix_ase_looks_user_id'), 'looks', ['user_id'], unique=False, schema='ase')
    op.create_index(op.f('ix_ase_looks_workspace_id'), 'looks', ['workspace_id'], unique=False, schema='ase')
    op.create_table('spree_messages',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content_redacted', sa.Text(), nullable=False),
    sa.Column('asset_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_id', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.Text(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('guardrail_verdict', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ase.spree_sessions.id'], name=op.f('fk_spree_messages_session_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spree_messages')),
    schema='ase'
    )
    op.create_index(op.f('ix_ase_spree_messages_expires_at'), 'spree_messages', ['expires_at'], unique=False, schema='ase')
    op.create_table('style_reference_images',
    sa.Column('style_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('fabric_type', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('license_type', sa.Text(), nullable=True),
    sa.Column('license_document', sa.Text(), nullable=True),
    sa.Column('attribution', sa.Text(), nullable=True),
    sa.Column('model_release', sa.Boolean(), nullable=True),
    sa.Column('generated', sa.Boolean(), nullable=False),
    sa.Column('stylist_approved_by', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['style_id'], ['ase.style_library.id'], name=op.f('fk_style_reference_images_style_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_style_reference_images')),
    schema='ase'
    )
    op.create_table('action_events',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('look_id', sa.UUID(), nullable=True),
    sa.Column('surface', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['gateway.users.id'], name=op.f('fk_action_events_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_events')),
    schema='gateway'
    )
    op.create_index(op.f('ix_gateway_action_events_user_id'), 'action_events', ['user_id'], unique=False, schema='gateway')
    op.create_index(op.f('ix_gateway_action_events_workspace_id'), 'action_events', ['workspace_id'], unique=False, schema='gateway')
    op.create_table('auth_identities',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('provider_uid', sa.Text(), nullable=False),
    sa.Column('email_enc', faue_db.types.EncryptedStr(), nullable=True),
    sa.Column('email_bidx', faue_db.types.BlindIndex(length=64), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_enc', faue_db.types.EncryptedStr(), nullable=True),
    sa.Column('phone_bidx', faue_db.types.BlindIndex(length=64), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['gateway.users.id'], name=op.f('fk_auth_identities_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_identities')),
    sa.UniqueConstraint('provider', 'provider_uid', name=op.f('uq_auth_identities_provider')),
    schema='gateway'
    )
    op.create_index('ix_auth_identities_email_bidx', 'auth_identities', ['email_bidx'], unique=False, schema='gateway', postgresql_where=None)
    op.create_table('body_profile',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('body_shape', sa.Text(), nullable=True),
    sa.Column('height_cm_enc', faue_db.types.EncryptedStr(), nullable=True),
    sa.Column('measurements_enc', faue_db.types.EncryptedStr(), nullable=True),
    sa.Column('fit_preference', sa.Text(), nullable=True),
    sa.Column('sizes_by_category', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['gateway.users.id'], name=op.f('fk_body_profile_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_body_profile')),
    schema='gateway'
    )
    op.create_index(op.f('ix_gateway_body_profile_workspace_id'), 'body_profile', ['workspace_id'], unique=False, schema='gateway')
    op.create_table('consents',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('policy_version', sa.Text(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['gateway.users.id'], name=op.f('fk_consents_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'purpose', name=op.f('pk_consents')),
    schema='gateway'
    )
    op.create_index(op.f('ix_gateway_consents_workspace_id'), 'consents', ['workspace_id'], unique=False, schema='gateway')
    op.create_table('feedback_signals',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.Text(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('signal', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['gateway.users.id'], name=op.f('fk_feedback_signals_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback_signals')),
    sa.UniqueConstraint('user_id', 'target_type', 'target_id', name=op.f('uq_feedback_signals_user_id')),
    schema='gateway'
    )
    op.create_index(op.f('ix_gateway_feedback_signals_workspace_id'), 'feedback_signals', ['workspace_id'], unique=False, schema='gateway')
    op.create_table('integration_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('provider_uid', sa.Text(), nullable=False),
    sa.Column('access_token_enc', faue_db.types.EncryptedStr(), nullable=False),
    sa.Column('refresh_token_enc', faue_db.types.EncryptedStr(), nullable=True),
    sa.Column('scopes', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('sync_cursor', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['gateway.users.id'], name=op.f('fk_integration_accounts_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_accounts')),
    sa.UniqueConstraint('user_id', 'provider', name=op.f('uq_integration_accounts_user_id')),
    schema='gateway'
    )
    op.create_index(op.f('ix_gateway_integration_accounts_workspace_id'), 'integration_accounts', ['workspace_id'], unique=False, schema='gateway')
    op.create_table('notify_devices',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('token_enc', faue_db.types.EncryptedStr(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['gateway.users.id'], name=op.f('fk_notify_devices_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notify_devices')),
    schema='gateway'
    )
    op.create_index(op.f('ix_gateway_notify_devices_workspace_id'), 'notify_devices', ['workspace_id'], unique=False, schema='gateway')
    op.create_table('notify_inbox',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('deeplink', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['gateway.users.id'], name=op.f('fk_notify_inbox_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notify_inbox')),
    schema='gateway'
    )
    op.create_index(op.f('ix_gateway_notify_inbox_user_id'), 'notify_inbox', ['user_id'], unique=False, schema='gateway')
    op.create_index(op.f('ix_gateway_notify_inbox_workspace_id'), 'notify_inbox', ['workspace_id'], unique=False, schema='gateway')
    op.create_table('notify_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start', sa.SmallInteger(), nullable=True),
    sa.Column('quiet_hours_end', sa.SmallInteger(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['gateway.users.id'], name=op.f('fk_notify_preferences_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'category', 'channel', name=op.f('pk_notify_preferences')),
    schema='gateway'
    )
    op.create_index(op.f('ix_gateway_notify_preferences_workspace_id'), 'notify_preferences', ['workspace_id'], unique=False, schema='gateway')
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=24), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('gender_presentation', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('geohash5', sa.String(length=5), nullable=True),
    sa.Column('locale', sa.Text(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('avatar_asset_id', sa.UUID(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['gateway.users.id'], name=op.f('fk_profiles_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_profiles')),
    sa.UniqueConstraint('username', name=op.f('uq_profiles_username')),
    schema='gateway'
    )
    op.create_index(op.f('ix_gateway_profiles_workspace_id'), 'profiles', ['workspace_id'], unique=False, schema='gateway')
    op.create_table('quiz_responses',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('quiz_version', sa.Text(), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['gateway.users.id'], name=op.f('fk_quiz_responses_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_responses')),
    schema='gateway'
    )
    op.create_index(op.f('ix_gateway_quiz_responses_user_id'), 'quiz_responses', ['user_id'], unique=False, schema='gateway')
    op.create_index(op.f('ix_gateway_quiz_responses_workspace_id'), 'quiz_responses', ['workspace_id'], unique=False, schema='gateway')
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('rotated_from', sa.UUID(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['gateway.users.id'], name=op.f('fk_refresh_tokens_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash')),
    schema='gateway'
    )
    op.create_index(op.f('ix_gateway_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False, schema='gateway')
    op.create_table('saved_looks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('look_id', sa.UUID(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['gateway.users.id'], name=op.f('fk_saved_looks_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_looks')),
    sa.UniqueConstraint('user_id', 'look_id', name=op.f('uq_saved_looks_user_id')),
    schema='gateway'
    )
    op.create_index(op.f('ix_gateway_saved_looks_workspace_id'), 'saved_looks', ['workspace_id'], unique=False, schema='gateway')
    op.create_table('style_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dna_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dna_dominant', sa.String(length=2), nullable=True),
    sa.Column('dna_alter_ego', sa.String(length=2), nullable=True),
    sa.Column('dna_wildcard', sa.String(length=2), nullable=True),
    sa.Column('tagline', sa.Text(), nullable=True),
    sa.Column('blend_line', sa.Text(), nullable=True),
    sa.Column('personal_line', sa.Text(), nullable=True),
    sa.Column('quiz_completed', sa.Boolean(), nullable=False),
    sa.Column('quiz_version', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retake_available_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['gateway.users.id'], name=op.f('fk_style_preferences_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_style_preferences')),
    schema='gateway'
    )
    op.create_index(op.f('ix_gateway_style_preferences_workspace_id'), 'style_preferences', ['workspace_id'], unique=False, schema='gateway')
    op.create_table('vault_items',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('subcategory', sa.Text(), nullable=True),
    sa.Column('colors', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('fabric', sa.Text(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('wear_count', sa.Integer(), nullable=False),
    sa.Column('last_worn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['gateway.users.id'], name=op.f('fk_vault_items_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vault_items')),
    schema='gateway'
    )
    op.create_index(op.f('ix_gateway_vault_items_user_id'), 'vault_items', ['user_id'], unique=False, schema='gateway')
    op.create_index(op.f('ix_gateway_vault_items_workspace_id'), 'vault_items', ['workspace_id'], unique=False, schema='gateway')
    op.create_table('wear_log',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('item_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('look_id', sa.UUID(), nullable=True),
    sa.Column('occasion', sa.Text(), nullable=True),
    sa.Column('worn_on', sa.Date(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['gateway.users.id'], name=op.f('fk_wear_log_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wear_log')),
    schema='gateway'
    )
    op.create_index(op.f('ix_gateway_wear_log_user_id'), 'wear_log', ['user_id'], unique=False, schema='gateway')
    op.create_index(op.f('ix_gateway_wear_log_workspace_id'), 'wear_log', ['workspace_id'], unique=False, schema='gateway')
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['gateway.users.id'], name=op.f('fk_workspace_members_user_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['gateway.workspaces.id'], name=op.f('fk_workspace_members_workspace_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'user_id', name=op.f('pk_workspace_members')),
    schema='gateway'
    )
    # ### end Alembic commands ###

    # Partial HNSW index per model_id.
    #
    # The column is deliberately dimensionless so several embedding models can
    # coexist during a migration. pgvector cannot index a dimensionless column,
    # so the index casts to the model's dimension in an expression and is
    # partial on model_id.
    #
    # QUERIES MUST USE THE SAME CAST to hit the index:
    #     ORDER BY embedding::vector(768) <=> $1::vector(768)
    #     WHERE model_id = 'open_clip/ViT-L-14-336'
    op.execute("""
        CREATE INDEX idx_vault_emb_hnsw_cliplarge ON ase.vault_embeddings
          USING hnsw ((embedding::vector(768)) vector_cosine_ops)
          WITH (m = 16, ef_construction = 64)
          WHERE model_id = 'open_clip/ViT-L-14-336'
    """)
    op.execute("""
        CREATE INDEX idx_style_emb_hnsw_cliplarge ON ase.style_embeddings
          USING hnsw ((embedding::vector(768)) vector_cosine_ops)
          WITH (m = 16, ef_construction = 64)
          WHERE model_id = 'open_clip/ViT-L-14-336'
    """)
    op.execute("""
        CREATE INDEX idx_aspiration_emb_hnsw_cliplarge ON ase.aspiration_embeddings
          USING hnsw ((embedding::vector(768)) vector_cosine_ops)
          WITH (m = 16, ef_construction = 64)
          WHERE model_id = 'open_clip/ViT-L-14-336'
    """)

    # Per-service grants. Cross-schema access fails at the DATABASE, not by
    # convention — that is what keeps a shared migration project from becoming
    # a shared free-for-all.
    op.execute("GRANT USAGE ON SCHEMA gateway TO faue_gateway")
    op.execute("GRANT USAGE ON SCHEMA ase TO faue_ase")
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA gateway TO faue_gateway")
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ase TO faue_ase")
    op.execute("GRANT USAGE ON ALL SEQUENCES IN SCHEMA gateway TO faue_gateway")
    op.execute("GRANT USAGE ON ALL SEQUENCES IN SCHEMA ase TO faue_ase")

    # Append-only tables: the service role may insert and read, never rewrite.
    op.execute("REVOKE UPDATE, DELETE ON gateway.audit_log FROM faue_gateway")
    op.execute("REVOKE UPDATE, DELETE ON gateway.quiz_responses FROM faue_gateway")


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ase.idx_vault_emb_hnsw_cliplarge")
    op.execute("DROP INDEX IF EXISTS ase.idx_style_emb_hnsw_cliplarge")
    op.execute("DROP INDEX IF EXISTS ase.idx_aspiration_emb_hnsw_cliplarge")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspace_members', schema='gateway')
    op.drop_index(op.f('ix_gateway_wear_log_workspace_id'), table_name='wear_log', schema='gateway')
    op.drop_index(op.f('ix_gateway_wear_log_user_id'), table_name='wear_log', schema='gateway')
    op.drop_table('wear_log', schema='gateway')
    op.drop_index(op.f('ix_gateway_vault_items_workspace_id'), table_name='vault_items', schema='gateway')
    op.drop_index(op.f('ix_gateway_vault_items_user_id'), table_name='vault_items', schema='gateway')
    op.drop_table('vault_items', schema='gateway')
    op.drop_index(op.f('ix_gateway_style_preferences_workspace_id'), table_name='style_preferences', schema='gateway')
    op.drop_table('style_preferences', schema='gateway')
    op.drop_index(op.f('ix_gateway_saved_looks_workspace_id'), table_name='saved_looks', schema='gateway')
    op.drop_table('saved_looks', schema='gateway')
    op.drop_index(op.f('ix_gateway_refresh_tokens_family_id'), table_name='refresh_tokens', schema='gateway')
    op.drop_table('refresh_tokens', schema='gateway')
    op.drop_index(op.f('ix_gateway_quiz_responses_workspace_id'), table_name='quiz_responses', schema='gateway')
    op.drop_index(op.f('ix_gateway_quiz_responses_user_id'), table_name='quiz_responses', schema='gateway')
    op.drop_table('quiz_responses', schema='gateway')
    op.drop_index(op.f('ix_gateway_profiles_workspace_id'), table_name='profiles', schema='gateway')
    op.drop_table('profiles', schema='gateway')
    op.drop_index(op.f('ix_gateway_notify_preferences_workspace_id'), table_name='notify_preferences', schema='gateway')
    op.drop_table('notify_preferences', schema='gateway')
    op.drop_index(op.f('ix_gateway_notify_inbox_workspace_id'), table_name='notify_inbox', schema='gateway')
    op.drop_index(op.f('ix_gateway_notify_inbox_user_id'), table_name='notify_inbox', schema='gateway')
    op.drop_table('notify_inbox', schema='gateway')
    op.drop_index(op.f('ix_gateway_notify_devices_workspace_id'), table_name='notify_devices', schema='gateway')
    op.drop_table('notify_devices', schema='gateway')
    op.drop_index(op.f('ix_gateway_integration_accounts_workspace_id'), table_name='integration_accounts', schema='gateway')
    op.drop_table('integration_accounts', schema='gateway')
    op.drop_index(op.f('ix_gateway_feedback_signals_workspace_id'), table_name='feedback_signals', schema='gateway')
    op.drop_table('feedback_signals', schema='gateway')
    op.drop_index(op.f('ix_gateway_consents_workspace_id'), table_name='consents', schema='gateway')
    op.drop_table('consents', schema='gateway')
    op.drop_index(op.f('ix_gateway_body_profile_workspace_id'), table_name='body_profile', schema='gateway')
    op.drop_table('body_profile', schema='gateway')
    op.drop_index('ix_auth_identities_email_bidx', table_name='auth_identities', schema='gateway', postgresql_where=None)
    op.drop_table('auth_identities', schema='gateway')
    op.drop_index(op.f('ix_gateway_action_events_workspace_id'), table_name='action_events', schema='gateway')
    op.drop_index(op.f('ix_gateway_action_events_user_id'), table_name='action_events', schema='gateway')
    op.drop_table('action_events', schema='gateway')
    op.drop_table('style_reference_images', schema='ase')
    op.drop_index(op.f('ix_ase_spree_messages_expires_at'), table_name='spree_messages', schema='ase')
    op.drop_table('spree_messages', schema='ase')
    op.drop_index(op.f('ix_ase_looks_workspace_id'), table_name='looks', schema='ase')
    op.drop_index(op.f('ix_ase_looks_user_id'), table_name='looks', schema='ase')
    op.drop_table('looks', schema='ase')
    op.drop_table('accessory_pairings', schema='ase')
    op.drop_table('workspaces', schema='gateway')
    op.drop_table('users', schema='gateway')
    op.drop_index(op.f('ix_gateway_outbox_published_at'), table_name='outbox', schema='gateway')
    op.drop_table('outbox', schema='gateway')
    op.drop_index(op.f('ix_gateway_notify_deliveries_workspace_id'), table_name='notify_deliveries', schema='gateway')
    op.drop_table('notify_deliveries', schema='gateway')
    op.drop_index(op.f('ix_gateway_deletion_ledger_sla_due_at'), table_name='deletion_ledger', schema='gateway')
    op.drop_table('deletion_ledger', schema='gateway')
    op.drop_index(op.f('ix_gateway_audit_log_target_id'), table_name='audit_log', schema='gateway')
    op.drop_index(op.f('ix_gateway_audit_log_actor_id'), table_name='audit_log', schema='gateway')
    op.drop_table('audit_log', schema='gateway')
    op.drop_table('admin_users', schema='gateway')
    op.drop_table('weather_cache', schema='ase')
    op.drop_index(op.f('ix_ase_vault_embeddings_workspace_id'), table_name='vault_embeddings', schema='ase')
    op.drop_index(op.f('ix_ase_vault_embeddings_user_id'), table_name='vault_embeddings', schema='ase')
    op.drop_table('vault_embeddings', schema='ase')
    op.drop_index(op.f('ix_ase_user_style_context_workspace_id'), table_name='user_style_context', schema='ase')
    op.drop_table('user_style_context', schema='ase')
    op.drop_table('style_library', schema='ase')
    op.drop_table('style_embeddings', schema='ase')
    op.drop_index(op.f('ix_ase_spree_sessions_workspace_id'), table_name='spree_sessions', schema='ase')
    op.drop_table('spree_sessions', schema='ase')
    op.drop_index(op.f('ix_ase_outbox_published_at'), table_name='outbox', schema='ase')
    op.drop_table('outbox', schema='ase')
    op.drop_index(op.f('ix_ase_model_calls_task'), table_name='model_calls', schema='ase')
    op.drop_index(op.f('ix_ase_model_calls_created_at'), table_name='model_calls', schema='ase')
    op.drop_table('model_calls', schema='ase')
    op.drop_index(op.f('ix_ase_look_jobs_workspace_id'), table_name='look_jobs', schema='ase')
    op.drop_index(op.f('ix_ase_look_jobs_user_id'), table_name='look_jobs', schema='ase')
    op.drop_index(op.f('ix_ase_look_jobs_status'), table_name='look_jobs', schema='ase')
    op.drop_table('look_jobs', schema='ase')
    op.drop_index(op.f('ix_ase_look_impressions_workspace_id'), table_name='look_impressions', schema='ase')
    op.drop_table('look_impressions', schema='ase')
    op.drop_index(op.f('ix_ase_fabric_embeddings_workspace_id'), table_name='fabric_embeddings', schema='ase')
    op.drop_table('fabric_embeddings', schema='ase')
    op.drop_index(op.f('ix_ase_fabric_analyses_workspace_id'), table_name='fabric_analyses', schema='ase')
    op.drop_table('fabric_analyses', schema='ase')
    op.drop_table('budgets', schema='ase')
    op.drop_index(op.f('ix_ase_aspiration_embeddings_workspace_id'), table_name='aspiration_embeddings', schema='ase')
    op.drop_index(op.f('ix_ase_aspiration_embeddings_user_id'), table_name='aspiration_embeddings', schema='ase')
    op.drop_table('aspiration_embeddings', schema='ase')
    op.drop_index(op.f('ix_ase_agent_runs_workspace_id'), table_name='agent_runs', schema='ase')
    op.drop_table('agent_runs', schema='ase')
    op.drop_index(op.f('ix_ase_agent_memory_workspace_id'), table_name='agent_memory', schema='ase')
    op.drop_table('agent_memory', schema='ase')
    # ### end Alembic commands ###
